version: "3.9"

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  
  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - dbdata2:/var/lib/mysql
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: idan
      MYSQL_PASSWORD: correcthorsebatterystaple
      MYSQL_ROOT_PASSWORD: correcthorsebatterystaple
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "9000:9000"
    networks:
      - laravel
  
  redis:
    container_name: redis
    image: "redis:alpine"
    restart: always
    command: redis-server --port 6360
    volumes:
    - ./data:/data
    ports:
    - "6379:6360"
    networks:
      - laravel

volumes:
  dbdata2:
    driver: local
